### ISSUE TITLE
Could not load Microsoft.O365.Security.Native.ETW in C# .NET 6.0

### ISSUE THREAD

**Issue by gleen-code** [microsoft/krabsetw#238]
Hi, 

I am using C# with the .NET 6.0 framework and trying to use the NuGet Microsoft.O365.Security.Native.ETW package (https://www.nuget.org/packages/Microsoft.O365.Security.Native.ETW/).

Although all the dependencies are resolved and the library is installed correctly, at run it says that it cannot load the library. This is the exception:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.O365.Security.Native.ETW, Version=1.0.8668.31639, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
  Source=MyProject
```

Inspecting the library dependencies, in the folder where it has been compiled, I can see that `ijwhost.dll` is not found.

![TM5qGN3J](https://github.com/microsoft/krabsetw/assets/172205026/b6cb3893-1d8f-4d4a-819a-8c691f24ecf6)

Although the dependency is located in the same directory, in the following path: `runtimes\win-x64\native\Ijwhost.dll`

This is the directory `bin\Debug\net6.0-windows7.0` structure:

- [My project files]
- `Microsoft.O365.Security.Native.ETW.dll`
- `runtimes\win-x64\native`
   - `Ijwhost.dll`

If I change the .NET framework version to 5.0, everything works fine. Above 6.0, it does not work with any version. Any ideas?

**Comment by swannman** [comment]
A bit of background:
- C++/CLI code needs to reference Ijwhost.dll at runtime in order to start up the .NET Core runtime. Here are a few references re: ljwhost.dll: [[1](https://github.com/dotnet/runtime/issues/38231)], [[2](https://learn.microsoft.com/en-us/dotnet/core/porting/cpp-cli)]. 
- We followed [this guidance](https://github.com/dotnet/sdk/issues/24310) to include it in the runtimes\win-x64\native\ directory. 
- Unfortunately. DLLs from the \runtimes\ directory aren't automatically copied to the output directory unless you do a `dotnet publish`. More on that behavior [here](https://stackoverflow.com/questions/52397501/nuget-references-to-assemblies-in-runtimes-folder-not-added) and [here](https://github.com/NuGet/Home/issues/7316). 

The best way we've found to get the DLL into the output directory is to edit the .csproj file and add an msbuild copy step:
 
`  <ItemGroup>`
`    <PackageReference Include="Microsoft.O365.Security.Native.ETW" Version="4.3.2">`
**`      <GeneratePathProperty>true</GeneratePathProperty>`**
`    </PackageReference>`
`  </ItemGroup>`

**`  <Target Name="CopyFiles" AfterTargets="Build">`**
**`    <ItemGroup>`**
**`      <File Include="$(PkgMicrosoft_O365_Security_Native_ETW)\runtimes\win-x64\native\Ijwhost.dll"></File>`**
**`    </ItemGroup>`**
**`    <Copy SourceFiles="@(File)" DestinationFolder="$(OutDir)"></Copy>`**
**`  </Target>`**

Want to give this a try and let us know whether it works?

**Comment by gleen-code** [comment]
Thank you very much, @swannman. That's works and makes sense.

I think you should document this, I've found more people with the same issue, and it's not very intuitive to solve.

Another problem that occurred to me after solving this one was the following:

![image](https://github.com/microsoft/krabsetw/assets/172205026/86ffa352-c0c5-4622-96d7-205c46f18b14)

```
at _CxxThrowException(Void* , _s__ThrowInfo* )
   at krabs.check_com_hr(Int32 hr)
   at krabs.provider<unsigned __int64>.{ctor}(provider<unsigned __int64>* , basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* providerName)
   at Microsoft.O365.Security.ETW.NativePtr<krabs::provider<unsigned __int64> >..ctor(basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* <args_0>)
   at Microsoft.O365.Security.ETW.Provider..ctor(String providerName)
```

If you use this library using the attribute [`STAThread`](https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/ms182351(v=vs.80)?redirectedfrom=MSDN), it does not work. Removing that it works, but it is still necessary if you using windows forms.
