### ISSUE TITLE
Stacktrace in Kernel ETW - example?

### ISSUE THREAD

**Issue by dobin** [microsoft/krabsetw#251]
There is a nice native User ETW stacktrace example which works well:
https://github.com/microsoft/krabsetw/blob/master/examples/NativeExamples/user_trace_008_stacktrace.cpp

and/from https://github.com/microsoft/krabsetw/pull/204/commits/b9ea01629e6906c442d516cb4dcf3db45338f6c9 by @jdu2600 

But there seems to be no example on how to use Kernel-ETW stacktrace. 

I found an example at https://github.com/microsoft/krabsetw/blob/af17f4c79ad350a976bf9c61e05554e1cffc27dc/krabs/krabs/trace.hpp#L142 
```
        * <example>
        *    krabs::guid id(L"{A0C1853B-5C40-4B15-8766-3CF1C58F985A}");
        *    provider<> powershell(id);
        *    powershell.trace_flags(EVENT_ENABLE_PROPERTY_STACK_TRACE);
        *    auto flags = powershell.get_trace_flags(); 
        *    assert(flags == EVENT_ENABLE_PROPERTY_STACK_TRACE);
        * </example>
```

But could not get it to work. 

There is also a "stackwalk" GUID at https://github.com/microsoft/krabsetw/blob/af17f4c79ad350a976bf9c61e05554e1cffc27dc/krabs/krabs/kernel_guids.hpp#L166 which confuses me, as it seems to be a dedicated GUID to trace from? But a stacktrace should be a property of other ETW events. 

The above example also mentions `Adjust SE_SYSTEM_PROFILE_NAME token privilege through AdjustTokenPrivileges(...) to enable stack tracing (not done in this example).` is this really a hard requirement, and how to adjust it exactly?

#199 seems to struggle too. 

**Is it possible to provide a native example, showing how to get stacktrace with kernel ETW?**

Loosely related, there also seems only one example on how to use `krabs::kernel_provider`, which shows what parameter it expects which is https://github.com/microsoft/krabsetw/blob/master/examples/NativeExamples/kernel_trace_002.cpp#L39 . 
```
    krabs::kernel_provider hive_provider(GUID_NULL, PERF_REG_HIVE);
```
Which is also confusing, as GUID_NULL seems to be used as "SOME_ULONG_FLAG_VALUE", while the actual GUID is the second parameter:
```
krabs::kernel_provider provider(SOME_ULONG_FLAG_VALUE, SOME_GUID)
```

It is not quiet clear for me how the first parameter should be used, and if i could add the EVENT_ENABLE_PROPERTY_STACK_TRACE flag there.

**Comment by jdu2600** [comment]
The legacy kernel (aka system) providers don't support all of the modern provider options.
In particular they just ignore `EVENT_ENABLE_PROPERTY_STACK_TRACE`. 😢 

There is a legacy mechanism though - [`TraceSetInformation(TraceStackTracingInfo)`](https://learn.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-tracesetinformation)
These stack traces are emitted as [separate events](https://learn.microsoft.com/en-us/windows/win32/etw/stackwalk-event) though. This is the (system) stackwalk guid that you noticed.

And that code snippet is the example of how to do this with this library.
https://github.com/microsoft/krabsetw/blob/af17f4c79ad350a976bf9c61e05554e1cffc27dc/krabs/krabs/trace.hpp#L133-L145

**Comment by jdu2600** [comment]
> Loosely related, there also seems only one example on how to use `krabs::kernel_provider`, which shows what parameter it expects which is https://github.com/microsoft/krabsetw/blob/master/examples/NativeExamples/kernel_trace_002.cpp#L39 .
> 
> ```
>     krabs::kernel_provider hive_provider(GUID_NULL, PERF_REG_HIVE);
> ```

Most of the kernel provider have convenience constructors defined which is why there aren't any good examples.
See https://github.com/microsoft/krabsetw/blob/master/krabs/krabs/kernel_providers.hpp


> Which is also confusing, as GUID_NULL seems to be used as "SOME_ULONG_FLAG_VALUE", while the actual GUID is the second parameter:
> 
> ```
> krabs::kernel_provider provider(SOME_ULONG_FLAG_VALUE, SOME_GUID)
> ```

There are two constructors - depending on whether you are enabling via flag (documented) or group mask (semi-documented).

https://github.com/microsoft/krabsetw/blob/af17f4c79ad350a976bf9c61e05554e1cffc27dc/krabs/krabs/provider.hpp#L320-L349

**Comment by dobin** [comment]
Thanks for the detailed information, that clears up my confusion! And based on #220 and #218 there seems to be no benefits using kernel-ETW ("system provider") compared to user-ETW: its not better, more secure, more detailed, or more trustworthy than user-ETW, and contains the same information. Together with the weird callstack handling as separate events, I dont see a point attempting to implement functionality for kernel-ETW (for https://github.com/dobin/RedEdr). 

Kernel-ETW is like a red herring: it sounds cool and better than user-ETW, but is basically the legacy system (as I understood it). And happens to have a convenient interface in KrabsETW.

**Comment by jdu2600** [comment]
Nice project. 😃 

The modern providers are definitely preferred if available.
There are still some niche events only available via the legacy system provider though.

Some projects that you might be interested in -
* https://github.com/jdu2600/conference_talks/blob/main/2024-07-bsidesbne-KernelETW.pdf
* https://github.com/jdu2600/Windows10EtwEvents - greppable ETW events
* https://github.com/jdu2600/Etw-SyscallMonitor - interesting kernel events
* https://github.com/jdu2600/ETW-PPL-Tester - ETW-TI via BYOD (rather than TestSigning)
* https://github.com/rabbitstack/fibratus - ETW
* https://github.com/peasead/elastic-container - Elastic EDR is free, and you can bump event verbosity for red team use cases
* https://github.com/microsoft/perfview - kernel events used for performance monitoring

**Comment by dobin** [comment]
Thanks for the links. I know your work ;-)

I didnt know Fibratus. Looks very interesting, similar idea. 

Also Joe's Sandbox has detailed memory allocation / protection changes listed, and is similar too. 

Anyway here's the wrong place for a discussion, i opened https://github.com/dobin/RedEdr/issues/2
